default: &default
  adapter: postgresql
  host: localhost
  port: 5432
  schema_search_path: public
  template: template0
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: fatima_college_new

test:
  <<: *default
  database: fatima_college_new

production:
  <<: *default
  database: d4kacgmf3iohb1
  username: tljvdckjvlpxpc
  password: c89d7b6c31a9dbbadbeef859599bd2087bb43563fbfc24b476285ff47dfd1292
  host: ec2-50-17-236-15.compute-1.amazonaws.com
  port: 5432